name: Build & Deploy Firmware to GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build firmware with Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/project \
          -w /project \
          espressif/idf idf.py build

    - name: Prepare firmware output
      run: |
        mkdir -p pages/firmware
        cp build/*.bin pages/firmware/
        cp build/*.elf pages/firmware/
        cp build/flasher_args.json pages/firmware/
        echo "<h1>ESP Firmware</h1><ul>" > pages/index.html
        for f in pages/firmware/*; do
          echo "<li><a href=\"$f\">$(basename $f)</a></li>" >> pages/index.html
        done
        echo "</ul>" >> pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages