name: Build ESP-IDF Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ESP-IDF
      uses: espressif/setup-esp-idf@v2  # Используем последнюю версию Action (v2)
      with:
        idf_version: 'v4.4'  # Указываем версию ESP-IDF, если нужно

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-venv
        python3 -m pip install --upgrade pip
        python3 -m pip install -r $IDF_PATH/requirements.txt

    - name: Set up ESP-IDF environment
      run: |
        . $IDF_PATH/export.sh

    - name: Build the project
      run: |
        idf.py build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: build/hello-world.bin