name: Build & Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build firmware
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            espressif/idf idf.py set-target esp32c3
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            espressif/idf idf.py build

      - name: Prepare firmware output for Pages
        run: |
          mkdir -p pages/firmware

          # Копируем все .bin
          cp build/*.bin pages/firmware/ || true

          # Получаем имя основного бинарника (можно настроить вручную)
          FIRMWARE_BIN=$(basename $(ls pages/firmware/*.bin | head -n 1))

          # manifest.json
          cat <<EOF > pages/manifest.json
          {
            "name": "ESP32 Hello World",
            "builds": [
              {
                "chipFamily": "ESP32C3",
                "parts": [
                  {
                    "path": "firmware/$FIRMWARE_BIN",
                    "offset": 0
                  }
                ]
              }
            ]
          }
          EOF

          # index.html с кнопкой и ссылками
          cat <<EOF > pages/index.html
          <!DOCTYPE html>
          <html lang="ru">
          <head>
            <meta charset="UTF-8">
            <title>ESP32 Hello World Flasher</title>
            <script type="module" src="https://unpkg.com/esp-web-tools@8.0.6/dist/web/install-button.js"></script>
          </head>
          <body>
            <h1>Прошивка ESP32 через браузер</h1>
            <esp-web-install-button manifest="manifest.json"></esp-web-install-button>

            <h2>Или скачайте прошивку вручную:</h2>
            <ul>
          EOF

          for f in pages/firmware/*.bin; do
            echo "  <li><a href=\"${f#pages/}\">$(basename "$f")</a></li>" >> pages/index.html
          done

          cat <<EOF >> pages/index.html
            </ul>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
