name: Build & Release ESP Firmware

on:
  push:
    tags:
      - 'v*'  # Например: v1.0.0, v2.3.4

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Docker (ESP-IDF)
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/project \
          -w /project \
          espressif/idf idf.py build

    - name: Upload firmware to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.bin
          build/*.elf
          build/flasher_args.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}