name: Build and Deploy ESP32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v5.1
        ./install.sh
        echo "IDF_PATH=$GITHUB_WORKSPACE/esp-idf" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/esp-idf/export.sh" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        . $GITHUB_WORKSPACE/esp-idf/export.sh
        idf.py build

    - name: Copy firmware to deployment dir
      run: |
        mkdir publish
        cp build/*.bin publish/
        cp build/bootloader/*.bin publish/
        cp build/partition_table/*.bin publish/

    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          build/*.bin
          build/bootloader/*.bin
          build/partition_table/*.bin